# Generated by Django 5.0.7 on 2024-07-13 18:01

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Tin nhắn', 'verbose_name_plural': 'Các tin nhắn'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Phòng', 'verbose_name_plural': 'Các phòng'},
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, error_messages={'unique': 'A user with that username already exists.'}, help_text='Bắt buộc. Tối đa 150 ký tự. Chỉ chữ cái, số và @/./+/-/_', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Tên đăng nhập'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(help_text='Nội dung tin nhắn', verbose_name='Tin nhắn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo tin nhắn', verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(help_text='Phòng gửi tin nhắn', on_delete=django.db.models.deletion.CASCADE, to='base.room', verbose_name='Phòng'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật tin nhắn', verbose_name='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(help_text='Người gửi', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo phòng', verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Nhập mô tả phòng', null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(help_text='Chọn chủ phòng', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Chủ phòng'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Nhập tên phòng', max_length=200, verbose_name='Tên phòng'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Chọn thành viên phòng', related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên'),
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(help_text='Chọn chủ đề phòng', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic', verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật phòng', verbose_name='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='Nhập tên chủ đề', max_length=200, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', help_text='Tải lên ảnh đại diện', null=True, upload_to='', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(help_text='Giới thiệu ngắn về bạn', null=True, verbose_name='Tiểu sử'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Nhập email của bạn', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Nhập tên của bạn', max_length=200, null=True, verbose_name='Tên'),
        ),
    ]
