# Generated by Django 5.0.7 on 2025-12-04 05:13

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(help_text='Chọn người tạo phòng', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo phòng'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Chọn thành viên tham gia', related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên'),
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(help_text='Chọn chủ đề cho phòng', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic', verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối', verbose_name='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(help_text='Giới thiệu ngắn về bản thân', null=True, verbose_name='Tiểu sử'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
